name: observability-stack

services:
  prometheus:
    # https://prometheus.io/docs/prometheus/latest/installation/
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    # https://prometheus.io/docs/prometheus/latest/command-line/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - "${PROMETHEUS_PORT:-9090}:9090"

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - "${GRAFANA_PORT:-3000}:3000"
    volumes:
     - 'grafana_storage:/var/lib/grafana'
    env_file:
      - ./grafana/config.monitoring
    restart: always
       
  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro                           # Root filesystem
      - /var/run:/var/run:ro                   # Docker run directory
      - /sys:/sys:ro                           # System filesystem
      - /var/lib/docker/:/var/lib/docker:ro    # Docker data directory
      - /dev/disk/:/dev/disk:ro                # Disk information
    privileged: true                            # Privileged mode for accessing system metrics
    devices:
      - /dev/kmsg  
    ports:
      - "${CADVISOR_PORT:-8080}:8080"
    restart: always

volumes:
  prometheus_data: {}
  grafana_storage: {}