name: observability-stack

services:
  prometheus:
    # https://prometheus.io/docs/prometheus/latest/installation/
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    # https://prometheus.io/docs/prometheus/latest/command-line/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - "${PROMETHEUS_PORT:-9090}:9090"

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - "${GRAFANA_PORT:-3000}:3000"
    volumes:
     - 'grafana_storage:/var/lib/grafana'
     - ./grafana/provisioning/:/etc/grafana/provisioning/
    restart: always
       
  cadvisor:
    image: google/cadvisor
    container_name: cadvisor
    volumes:
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "${CADVISOR_PORT:-8080}:8080"
    restart: always

volumes:
  prometheus_data: {}
  grafana_storage: {}